### PR TITLE
Update chemicalAllPrimary.rq

### PR DESCRIPTION
**Pull request by tabbassidaloii**
We don't need the compound names

### CODE REVIEW

**Comment by DeniseSl22** [comment]
Why not @tabbassidaloii ? I thought that was needed for the names2IDs? Wikidata has many more trivial names than ChEBI and HMDB for many compounds...

**Comment by tabbassidaloii** [comment]
There is a separate query "chemicalPrimarySynonyms.rq" for it, correct?

**Comment by DeniseSl22** [comment]
Yes, I need to check if that one also takes out all Primary IDs which do not have a label....

**Comment by DeniseSl22** [comment]
I remember again; if I add an "optional" for all the synonyms, the query times out.... So we have to perform two queries, one to get all Primary IDs (and their primary name if available), and one to get the synonyms (if available) for the primaries. @tabbassidaloii

**Pull request closed without merging**
